from __future__ import annotations

from copy import deepcopy


SAMPLE_JOBS: list[dict] = [
    {
        "source": "adzuna_sample",
        "source_job_id": "adz-001",
        "title": "Junior Data Engineer",
        "company": "DataNova",
        "location_city": "Paris",
        "location_region": "Ile-de-France",
        "location_country": "France",
        "description": "Build ELT pipelines with Python, SQL, PySpark, Airflow, Docker and Azure.",
        "salary_min": 38000,
        "salary_max": 45000,
        "contract_type": "CDI",
        "publication_date": "2026-08-20",
        "url": "https://example.com/jobs/adz-001",
    },
    {
        "source": "adzuna_sample",
        "source_job_id": "adz-002",
        "title": "Data Analyst BI",
        "company": "RetailScope",
        "location_city": "Lyon",
        "location_region": "Auvergne-Rhone-Alpes",
        "location_country": "France",
        "description": "Analyze sales data using SQL, Excel, Power BI, Tableau and PostgreSQL.",
        "salary_min": 35000,
        "salary_max": 42000,
        "contract_type": "CDI",
        "publication_date": "2026-08-18",
        "url": "https://example.com/jobs/adz-002",
    },
    {
        "source": "adzuna_sample",
        "source_job_id": "adz-003",
        "title": "Cloud Data Engineer",
        "company": "AzureWorks",
        "location_city": "Lille",
        "location_region": "Hauts-de-France",
        "location_country": "France",
        "description": "Design data lake solutions on Azure with Spark, Databricks, Docker, Git and Linux.",
        "salary_min": 50000,
        "salary_max": 62000,
        "contract_type": "CDI",
        "publication_date": "2026-08-14",
        "url": "https://example.com/jobs/adz-003",
    },
    {
        "source": "muse_sample",
        "source_job_id": "mus-001",
        "title": "Analytics Engineer",
        "company": "MetricLab",
        "location_city": "Remote",
        "location_region": "Remote",
        "location_country": "France",
        "description": "Model analytics datasets with DBT, SQL, Snowflake, Python and Git.",
        "salary_min": 43000,
        "salary_max": 54000,
        "contract_type": "Full-time",
        "publication_date": "2026-08-21",
        "url": "https://example.com/jobs/mus-001",
    },
    {
        "source": "muse_sample",
        "source_job_id": "mus-002",
        "title": "Big Data Developer",
        "company": "StreamFactory",
        "location_city": "Nantes",
        "location_region": "Pays de la Loire",
        "location_country": "France",
        "description": "Develop Spark, PySpark and Kafka pipelines on AWS and Kubernetes.",
        "salary_min": 47000,
        "salary_max": 58000,
        "contract_type": "CDI",
        "publication_date": "2026-08-19",
        "url": "https://example.com/jobs/mus-002",
    },
    {
        "source": "muse_sample",
        "source_job_id": "mus-003",
        "title": "Backend Data API Developer",
        "company": "OpenServe",
        "location_city": "Paris",
        "location_region": "Ile-de-France",
        "location_country": "France",
        "description": "Expose data products with FastAPI, PostgreSQL, Python, Docker and Azure.",
        "salary_min": 44000,
        "salary_max": 52000,
        "contract_type": "CDI",
        "publication_date": "2026-08-16",
        "url": "https://example.com/jobs/mus-003",
    },
    {
        "source": "scraping_sample",
        "source_job_id": "web-001",
        "title": "Data Platform Engineer",
        "company": "Lakehouse Studio",
        "location_city": "Bordeaux",
        "location_region": "Nouvelle-Aquitaine",
        "location_country": "France",
        "description": "Create data platform pipelines using Azure, Databricks, Airflow, SQL and Docker.",
        "salary_min": 48000,
        "salary_max": 61000,
        "contract_type": "CDI",
        "publication_date": "2026-08-17",
        "url": "https://example.com/jobs/web-001",
    },
    {
        "source": "scraping_sample",
        "source_job_id": "web-002",
        "title": "Junior BI Data Engineer",
        "company": "NorthData",
        "location_city": "Paris",
        "location_region": "Ile-de-France",
        "location_country": "France",
        "description": "Maintain PostgreSQL, Python, Excel and Airflow pipelines for dashboard teams.",
        "salary_min": 36000,
        "salary_max": 43000,
        "contract_type": "Apprenticeship",
        "publication_date": "2026-08-13",
        "url": "https://example.com/jobs/web-002",
    },
]


def get_sample_jobs(source_prefix: str | None = None) -> list[dict]:
    records = deepcopy(SAMPLE_JOBS)
    if source_prefix is None:
        return records
    return [record for record in records if record["source"].startswith(source_prefix)]

